org.tutorial.first_extension: # {group_id}.{name} from the knime.yml
  src: C:\KNIME\knime_4.6.0_dev\pure-python-knime-nodes\basic\tutorial_extension # Path to folder containing the extension files
  conda_env_path: C:\Users\tymsk\anaconda3\envs\my_python_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform
